App\EducationBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        category:
            type: string
            length: 255
        slug:
            type: string
            length: 255


