App\EducationBundle\Entity\Image:
    type: entity
    table: image_product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        image:
            type: string
            length: 255
        descimage:
            type: string
            length: 100
    manyToOne:
        product:
            targetEntity: Product
            inversedBy: image
            joinColumn:
                name: product_id
                referencedColumnName: id

