App\UserBundle\Entity\Users:
    reposytoryClass: App\UserBundle\Repository\UsersRepository
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
            photoMerchandiser:
            name:
                requare: true
            surname:
                requare: true
            middleName:
                requare: true
            birthday:
                type: datetime
                requare: true
            location:
                requare: true
            country:
                requare: true
            city:
                requare: true
            adress:
                requare: true
            phoneNumber:
                requare: true
            company:
                requare: true
            logoCompany:
            birthdayCompany:
                type: datetime
            merchandiser:
                type: boolean
                requare: true